# Train on normal data, test on everything
globals:
  seed: 1213
  device: cuda
  num_epochs: 50
  output_dir: ./training_output8/
  use_fold: 0
  target_sr: 32000

dataset:
  name: SpectrogramDataset
  params:
    img_size: 224
    melspectrogram_parameters:
      n_mels: 64
      n_fft: 2048
      hop_length: 512
      power: 2.0
      fmin: 20
      fmax: 8000
    metric_learning: True
    spectrogram_transforms: spec_augment

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

loader:
  train:
    batch_size: 24
    shuffle: True
    num_workers: 2
    pin_memory: False
    drop_last: True
  val:
    batch_size: 24
    shuffle: False
    num_workers: 2
    pin_memory: False
    drop_last: False

model:
  name: resnest50_fast_1s1x64d
  params:
    pretrained: True
    n_classes: 4

loss:
  name: BCEWithLogitsLoss
  params: {}

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10
